<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmail extends Datum
{
  public function setTableDefinition()
  {
    parent::setTableDefinition();
    $this->setTableName('email');
    $this->hasColumn('_from as from', 'string', 125, array('type' => 'string', 'length' => 125, 'nospace' => true));
    $this->hasColumn('_to as to', 'string', 125, array('type' => 'string', 'length' => 125, 'nospace' => true));
    $this->hasColumn('carbon_copy', 'string', null, array('type' => 'string', 'nospace' => true));
    $this->hasColumn('blind_carbon_copy', 'string', null, array('type' => 'string', 'nospace' => true));
    $this->hasColumn('message', 'string', null, array('type' => 'string'));
  }

}