<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmail extends Message
{
  public function setUp()
  {
    parent::setUp();
    $this->hasOne('Data', array('local' => 'data_id',
                                'foreign' => 'id',
                                'onDelete' => 'CASCADE'));
  }
}