default:
  http_metas:
    content-type: text/html

  metas:
    title:        <?php echo sfConfig::get('app_project_name') ?>
    description:  <?php echo sfConfig::get('app_project_description') ?>
    keywords:     <?php echo sfConfig::get('app_project_keywords') ?>
    language:     en
    robots:       noindex, nofollow

  stylesheets:    [main]

  has_layout:     on
  layout:         layout