<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Report extends BaseReport
{
    public function setLocation($value)
    {
        $this->_set('location', $value);
        
        if ($coordinates = GMap::getCoordinates(GMap::geocode($value))) {
            $this->Location = new Coordinate();
            $this->Location->Report = $this;
            $this->Location->latitude = $coordinates['latitude'];
            $this->Location->longitude = $coordinates['longitude'];
            $this->Location->save();
        } else {
            # flag
        }
    }
}