<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Report extends BaseReport
{
    public function setLocation($value)
    {
        $this->Location = new Coordinate();
        $this->Location->Report = $this;
        $this->Location->latitude = 1;
        $this->Location->longitude = 10;
        $this->Location->save();
    }
}