<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Report extends BaseReport
{
    public function setLocation($value)
    {
        $this->_set('location', $value);
        
        if ($coordinates = GMap::getCoordinates(GMap::geocode($value))) {
            $this->Point = new Coordinate();
            $this->Point->Report = $this;
            $this->Point->latitude = $coordinates['latitude'];
            $this->Point->longitude = $coordinates['longitude'];
            $this->Point->save();
        } else {
            //*
            var_dump(array(
                'value' => $value,
                'geocode' => GMap::geocode($value),
                'coordinates' => GMap::getCoordinates($value)
            ));
            //*/
            die();
        }
    }
}