rendering: ~
security:
    class: sfGuardBasicSecurityFilter

# insert your own filters here

cache:     ~
common:    ~
#  class: sfMinifyFilter 
#  param:
#    javascripts:    true
#    stylesheets:    false
execution: ~
