sms_/:
    url: /sms/:s_phone_number/:message/:r_phone_number/
    param: { module: sms, action: parse, message: '', r_phone_number: '' }
    
sms:
    url: /sms/:s_phone_number/:message/:r_phone_number
    param: { module: sms, action: parse, r_phone_number: '' }

##

account:
    url: /account
    param: { module: account, action: index }

##

sf_guard_signin:
    url:   /login
    param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
    url:   /logout
    param: { module: sfGuardAuth, action: signout }

sf_guard_password:
    url:   /request_password
    param: { module: sfGuardForgotPassword, action: password }
    
sf_guard_password_success:
    url:   /request_password/success
    param: { module: sfGuardForgotPassword, action: password_success }

sf_guard_forgot_password_reset_password:
    url:   /reset_password/:key/:id
    param: { module: sfGuardForgotPassword, action: reset_password }

sf_guard_register:
    url:   /register
    param: { module: sfGuardRegister, action: index }
    
sf_guard_register_confirm:
    url: /register/confirm/:key/:username
    param: { module: sfGuardRegister, action: confirm }

###

help:
    url: /help
    param: { module: default, action: help }

homepage:
    url:   /
    param: { module: default, action: index }
  
about:
    url: /about
    param: { module: default, action: about }

contact:
    url: /contact
    param: { module: default, action: contact }
    
terms:
    url: /terms
    param: { module: default, action: terms }
    
instructions:
    url: /instructions
    param: { module: default, action: instructions }
