default:
  http_metas:
    content-type: text/html

  metas:
    title:        <?php echo sfConfig::get('app_project_name') ?>
    description:  <?php echo sfConfig::get('app_project_description') ?>
    keywords:     <?php echo sfConfig::get('app_project_keywords') ?>
    language:     en
    robots:       noindex, nofollow

  stylesheets: 
     - blueprintcss/blueprint/src/reset.css
     - blueprintcss/blueprint/plugins/liquid/liquid.css
     - blueprintcss/blueprint/src/typography.css
     - blueprintcss/blueprint/src/forms.css
     - blueprintcss/blueprint/plugins/fancy-type/screen.css
     - blueprintcss/blueprint/plugins/tabs/screen.css
     - blueprintcss/blueprint/plugins/buttons/screen.css
     - main

  has_layout:     on
  layout:         layout