<?php require_once 'app.php'; ?>

all:
    project:
        name: 'HAB Watch'
        description: 'HAB Watch, Harmful Algal Bloom Watch'
        keywords: 'habwatch, hab, harmful, algal, bloom, poisonous, participatory sensing, urban sensing, cens'
        contact_email: 'contact@habwatch.com'
        participate_email: 'm@habwatch.com'
        uri: 'http://habwatch.com'

    outgoing:
        emails_from: 'no-reply@habwatch.com'

    smtp:
        username: <?= SMTP_USERNAME ?>
        password: <?= SMTP_PASSWORD ?>
    
    imap:
        uri: imap://<?= trim(SMTP_USERNAME) ?>:<?= trim(SMTP_PASSWORD) ?>@imap.gmail.com:993/INBOX#ssl

    doctrine:
        db_dsn: <?= DOCTRINE_DB_DSN ?>

    google:
        maps_key: <?= GOOGLE_MAPS_KEY ?>
        analytics: "'UA-5925745-3'"

    phlickr:
        lib_dir: <?= sfConfig::get('sf_lib_dir') ?>/vendor/phlickr

    flickr:
        api_key: <?= FLICKR_API_KEY ?>
        secret: <?= FLICKR_SECRET ?>
        token: <?= FLICKR_TOKEN ?>