<?php require 'app.php'; ?>

all:
    project:
        name: 'Merhab'
        contact_email: 'olmo.maldonado@gmail.com'
    
    outgoing:
        emails_from: 'no-reply@merhab.cens.ucla.edu'
        
    smtp:
        username: <?php echo $SMTP_USERNAME; ?>
        password: <?php echo $SMTP_PASSWORD; ?>
        
    doctrine:
        db_dsn: <?php echo $DOCTRINE_DB_DSN; ?>
        
    google:
        maps_key: <?php echo $GOOGLE_MAPS_KEY; ?>