<?php require 'app.php'; ?>

all:
    project:
        name: 'Merhab'
        contact_email: 'olmo.maldonado@gmail.com'
    smtp:
        username: <?php echo $SMTP_USERNAME; ?>
        password: <?php echo $SMTP_PASSWORD; ?>
        
    doctrine:
        db_dsn: <?php echo $DOCTRINE_DB_DSN; ?>
