Profile:
    columns:
        first_name: string(255)
        middle_name: string(255)
        last_name: string(255)
        
        sf_guard_user_id: integer(4)
        
    relations:
        User:
            class: sfGuardUser
            foreignType: one
            
        Emails:
            class: Email
            type: many
            local: id
            foreign: profile_id
            
Email:
    columns:
        address:
            type: string
            length: 100
            unique: true
        
        profile_id: integer
            
    relations:
        Profile:
            local: profile_id
            foreign: id
            onDelete: CASCADE
                