Profile:
  columns:
    sf_guard_user_id: integer(4)
    first_name: string(255)
    middle_name: string(255)
    last_name: string(255)
    
  relations:
    User:
      class: sfGuardUser
      foreignType: one