Profile:
    columns:
        first_name:
            type: string
            length: 128
            notnull: true

        middle_name: 
            type: string
            length: 100
            
        last_name: 
            type: string
            length: 100
            notnull: true
        
        sf_guard_user_id:
            type: integer
            length: 4
            notnull: true            
        
    relations:
        User:
            class: sfGuardUser
            foreignType: one
            onDelete: CASCADE
            
        Emails:
            class: EmailAddress
            type: many
            local: id
            foreign: profile_id
            
        Phones:
            class: PhoneNumber
            type: many
            local: id
            foreign: profile_id

EmailAddress:
    columns:
        address:
            type: string
            length: 100
            unique: true
            notnull: true
            nospace: true
        disabled:
            type: boolean
            default: false
        
        profile_id: integer
            
    relations:
        Profile:
            local: profile_id
            foreign: id
            onDelete: CASCADE

PhoneNumber:
    columns:
        number:
            type: string
            length: 14
            notnull: true
            nospace: true
        disabled:
            type: boolean
            default: false
            
        
        profile_id: integer
            
    relations:
        Profile:
            local: profile_id
            foreign: id
            onDelete: CASCADE

# From Partisan
Storage:
    columns:
        sf_guard_user_id:
            type: integer
            length: 4
            notnull: true
        
    relations:
        User:
            class: sfGuardUser
            foreignType: one
            onDelete: CASCADE

Datum:
    columns:
        file: blob
        
    relations:            
        Preference:
            type: one
            local: id
            foreign: datum_id

    actAs:
        Timestampable:

Preference:
    columns:
        enabled:
            type: boolean
            default: false

        # Foreign Keys
        datum_id: integer

    relations:            
        Datum:
            type: one
            local: datum_id
            foreign: id
            onDelete: CASCADE

    actAs:
        Timestampable:

Picture:
    inheritance:
        extends: Datum
        type: concrete
        
    columns:
        file:
            name: file as still
            type: blob
            
        resolution: integer
        
        quality:
            type: string
            length: 10
            
        format:
            type: string
            length: 25
            
    
        storage_id: integer            

    relations:
        Storage:
            type: one
            foreignType: many
            foreignAlias: Pictures
            onDelete: CASCADE        
            
GPS:
    columns:
        
    relations:
        Satellites:
            type: one
            local: id
            foreign: g_p_s_id

        Position:
            type: one
            local: id
            foreign: g_p_s_id

        Course:
            type: one
            local: id
            foreign: g_p_s_id

Satellites:
    inheritance:
        extends: Datum
        type: concrete

    columns:
        horizontal_dop: float
        
        used_satellites:
            type: integer
            length: 10
            
        vertical_dop: float
        
        time: float
        
        satellites:
            type: integer
            length: 10
            
        time_dop: float

        # Foreign Keys
        g_p_s_id: integer
        storage_id: integer            

    relations:
        Storage:
            type: one
            foreignType: many
            onDelete: CASCADE
            
        GPS:
            type: one
            local: g_p_s_id
            foreign: id
            owningSide: true

Position:
    tableName: position_table

    inheritance:
        extends: Datum
        type: concrete

    columns:
        latitude: float
        altitude: float
        vertical_accuracy: float
        longitude: float
        horizontal_accuracy: float

        # Foreign Keys
        g_p_s_id: integer
        storage_id: integer            

    relations:
        Storage:
            type: one
            foreignType: many
            foreignAlias: Positions
            onDelete: CASCADE
            
        GPS:
            type: one
            local: g_p_s_id
            foreign: id
            owningSide: true

Course:
    inheritance:
        extends: Datum
        type: concrete

    columns:
        speed: float
        heading: float
        heading_accuracy: float
        speed_accuracy: float

        # Foreign Keys
        g_p_s_id: integer
        storage_id: integer            

    relations:
        Storage:
            type: one
            foreignType: many
            foreignAlias: Courses
            onDelete: CASCADE
            
        GPS:
            type: one
            local: g_p_s_id
            foreign: id
            owningSide: true

# End of Partisan models
Message:
    inheritance:
        extends: Datum
        type: concrete
        
    columns:
        _from:
            name: _from as from
            type: string
            length: 125
            nospace: true
                    
        _to:
            name: _to as to
            type: string
            length: 125
            nospace: true
            
        message:
            type: string

        
        storage_id: integer            

    relations:
        Storage:
            type: one
            foreignType: many
            foreignAlias: Messages
            onDelete: CASCADE
SMS:
    inheritance:
        extends: Message
        type: column_aggregation
        
    columns:
        storage_id: integer            

    relations:
        Storage:
            type: one
            foreignType: many
            onDelete: CASCADE

Email:
    inheritance:
        extends: Message
        type: column_aggregation
        
    columns:
        carbon_copy:
            type: string
            nospace: true
            
        blind_carbon_copy:
            type: string
            nospace: true
            
        subject:
            type: string
    
        storage_id: integer            

    relations:
        Storage:
            type: one
            foreignType: many
            foreignAlias: Emails
            onDelete: CASCADE
            
Report:
    inheritance:
        extends: Datum
        type: concrete
        
    columns:
        quantity: integer
        condition: string
        subject: string
        location: string
        
        message_id: integer
        storage_id: integer
        
    relations:
        Message:
            type: one
            local: message_id
            foreign: id
        
        Storage:
            type: one
            foreignType: many
            foreignAlias: Reports
            onDelete: CASCADE
            
        Point:
            class: Coordinate
            type: one
            local: id
            foreign: report_id

Coordinate:
    inheritance:
        extends: Datum
        type: concrete
        
    columns:
        latitude: string
        longitude: string
    
        report_id: integer
        
    relations:
        Report:
            type: one
            local: report_id
            foreign: id
            onDelete: CASCADE
